### ISSUE TITLE
Refactor $tn-height and $tn-spacing variables

### ISSUE THREAD

**Issue by oysteinsigholt** [TelenorFrontend/component-library#16]
The **$tn-height** and **$tn-spacing** variables are not only for form-elements. Should they be moved to to **_variables/common.scss**?

**Comment by pkkummermo** [comment]
Agreed. They should at least have a global/common implementation which can be used outside of the form scope.

**Comment by tipsy** [comment]
Fixed by 617681cd23575ddde34cc08ad89665b06e817636 and d90d69fdc85b59e49eb3ab101b6216b1cf5118f6.
