### ISSUE TITLE
Add mixin for making elements no-selectable

### ISSUE THREAD

**Issue by pkkummermo** [TelenorFrontend/component-library#22]
Right now we're selecting the text of the radio/checkbox element if we click abit eagerly on the inputs. Should we add `user-select: none`?

**Comment by tipsy** [comment]
In Paulius' design nothing except text content (p, a, headings, lists, etc) is selectable. I think this is a good approach, but I haven't figured out how to best implement it yet.

**Comment by pkkummermo** [comment]
Best approach to start with is creating a `$tn-interaction--no-select` which we add explicitly to elements which shouldn't be selected. I'll change this issue to reflect that

**Comment by pkkummermo** [comment]
Fixed by @tipsy in #23
